### ISSUE TITLE
Why does the heap keep growing

### ISSUE THREAD

**Issue by opvexe** [mkevac/debugcharts#17]
![image](https://user-images.githubusercontent.com/26895243/90881070-17cf6700-e3dc-11ea-8fd3-2dd6e3df4770.png)

Why does the heap keep growing

Memory is not leaking and it keeps growing

**Comment by mkevac** [comment]
Well, this package only draws what Go's pprof gives it. So, the question is probably not for this project.
Can you give me an example of a program that you are using?

**Comment by xinyu412** [comment]
![image](https://user-images.githubusercontent.com/3425352/111724262-e77f7680-889f-11eb-8153-c1942611345b.png)
![image](https://user-images.githubusercontent.com/3425352/111724315-0120be00-88a0-11eb-9954-259c9088ccb4.png)

![image](https://user-images.githubusercontent.com/3425352/111724528-5f4da100-88a0-11eb-8e9d-0915f903e8e2.png)

so just implement a function like
```
func countHeap() int {
	n, _ := runtime.MemProfile(nil, false)
	return n
}
```  
and replace this line with it. 
`pprof.Lookup("heap").Count()`

**Comment by opvexe** [comment]
> ![image](https://user-images.githubusercontent.com/3425352/111724262-e77f7680-889f-11eb-8153-c1942611345b.png)
> ![image](https://user-images.githubusercontent.com/3425352/111724315-0120be00-88a0-11eb-9954-259c9088ccb4.png)
> 
> ![image](https://user-images.githubusercontent.com/3425352/111724528-5f4da100-88a0-11eb-8e9d-0915f903e8e2.png)
> 
> so just implement a function like
> 
> ```
> func countHeap() int {
> 	n, _ := runtime.MemProfile(nil, false)
> 	return n
> }
> ```
> 
> and replace this line with it.
> `pprof.Lookup("heap").Count()`

I dealt with it three months ago.

**Comment by opvexe** [comment]
I dealt with it three months ago.
