### ISSUE TITLE
calls to log.Fatal() make me nervous

### ISSUE THREAD

**Issue by dgryski** [mkevac/debugcharts#7]
Errors happen all the time at scale.  I'm hesitant to deploy a service to production built with this knowing that log.Fatal() might be called and my application would exit.  I think log.Println/return pair would be sufficient in most of the cases.

Alternatively have it configurable with a package-level variable.

**Comment by mkevac** [comment]
Sure. You are right.
I had it there cause I am using this package for debug only.
I will fix it right away.

**Comment by dgryski** [comment]
I'm also using it for debugging purposes.  I have a file containing

```go
// +build debugcharts

package main

import _ "github.com/mkevac/debugcharts"
```

so if I build with '-tags debugcharts' it's included in my binary.  (Maybe a nice snippet to add to the README?)

**Comment by mkevac** [comment]
Interesting way turning it on/off.
