### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by lengrongfu** [mkevac/debugcharts#9]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7ad1a0]

goroutine 19 [running]:
github.com/mkevac/debugcharts.(*server).gatherData(0xa9bc60)
        C:/golang/gowork/src/github.com/mkevac/debugcharts/debugcharts.go:112 +0x210
created by github.com/mkevac/debugcharts.init.1
        C:/golang/gowork/src/github.com/mkevac/debugcharts/debugcharts.go:158 +0x2f9
exit status 2
```

**Comment by mkevac** [comment]
Seems that [Times](https://godoc.org/github.com/shirou/gopsutil/process#Process.Times) function is not implemented for Microsoft Windows and I did not check the error returned.

**Comment by mkevac** [comment]
I check for an error now, but, unfortunately, CPU chart does not work for Microsoft Windows. This feature should be added to https://github.com/shirou/gopsutil
